##
# This file is part of the IVMS Online.
#
# @copyright 2023 © by Rafał Wrzeszcz - Wrzasq.pl.
##

AWSTemplateFormatVersion: "2010-09-09"

Transform:
    - "WrzasqPlCformMacro"

Resources:
    LicensesTable:
        Type: "AWS::DynamoDB::Table"
        DeletionPolicy: "Retain"
        Properties:
            KeySchema:
                -
                    AttributeName: "customerAndVesselId"
                    KeyType: "HASH"
                -
                    AttributeName: "licenseKey"
                    KeyType: "RANGE"
            PointInTimeRecoverySpecification:
                PointInTimeRecoveryEnabled: true
            BillingMode: "PAY_PER_REQUEST"

Outputs:
    LicensesTableName:
        Value: !Ref "LicensesTable"

    LicensesTableArn:
        Value: !GetAtt "LicensesTable.Arn"
